
import NavBar from "../../Components/NavBar/NavBar";
import { documentToReactComponents } from '@contentful/rich-text-react-renderer';
import styles from "./ArticleID.module.css"
import { createClient } from "contentful";
import { CopyBlock, dracula } from "react-code-blocks";
import { useEffect } from "react";
import { useState } from "react";
import Head from "next/head";
import { useRouter } from "next/router";
const client = createClient({
  space: process.env.CONTENTFUL_SPACE_ID,
  accessToken: process.env.CONTENTFUL_ACCESS_KEY
})

export async function getStaticPaths() {

  const res = await client.getEntries({
    content_type: "articleCards",
  })
  const paths = res.items.map((item) => {
    return {
      params: { id: item.fields.slug }
    }
  })
  return {
    paths,
    fallback: false
  }
}
export async function getStaticProps({ params }) {
  console.log(params)
  const { items } = await client.getEntries({
    content_type: "articlePage",
    "fields.slug": params.id
  })


  return {
    props: { article: items[0].fields }
  }
}

const ArticleTemplate = ({ article }) => {
  let router = useRouter()
  console.log(router.query.id)
  let [photo, setPhoto] = useState("")
  async function getPhoto() {
    let response = await fetch("/api/unsplash")
    let data = await response.json()
    setPhoto(data.name.urls.regular)
  }
  useEffect(() => {
    getPhoto()
  }, [])
  console.log(photo)
  return (
    <div >
      <Head>
        <title>{router.query.id} - Jordan Freelance</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/greyback.png" />
      </Head>
      <NavBar />
      <div style={{ backgroundImage: `url(${photo})` }}
        className={styles.Background}></div>
      <main className={styles.Main}>
        {documentToReactComponents(article.content)}

        {article.slug == "react-state-management" && <CopyBlock
          text={`
import React from 'react';
export let pageContext = React.createContext() 

function App() {

let [state,setState]=useState({
  name:"jordan",
  age:28
})

return (
  <pageContext.Provider value={{ state , setState }}>
      <div className="App">
          <NavBar/>
          <RandomComponent/>
      </div>
  <pageContext.Provider>
)`}
          language={"jsx"}
          showLineNumbers={true}
          wrapLines={true}
          theme={dracula}
        />}
        {documentToReactComponents(article.content2)}
        {article.slug == "react-state-management" && <CopyBlock
          text={`
import React from 'react';
import { PageContext } from "../App";

export default function Navbar() {

  let { state, setState } = useContext(pageContext)
  console.log(state)

  return (
    <nav>

    </nav>
  )`}
          language={"jsx"}
          showLineNumbers={true}
          wrapLines={true}
          theme={dracula}
        />}
      </main>

    </div>
  );
}

export default ArticleTemplate;