backend:
  name: git-gateway
  branch: main
media_folder: "/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads
collections:
  - name:"blog"
    label:"blog"
    folder:"/blog.md"
    create: true
    slug: "{{year}}-{{month}}-{{day}}_{{slug}}"
    fields:
      - { label:"Title",name:"title",widget:"string"}