import AboutHero from "../Components/AboutHero/AboutHero";
import LatestWork from "../Components/LatestWork/LatestWork"
import HowICanHelp from "../Components/HowICanHelp/HowICanHelp"
import FoundersNote from "../Components/FoundersNote/FoundersNote"
import NavBar from "../Components/NavBar/NavBar";
import AboutMe from "../Components/AboutMe/AboutMe.js";
import Head from "next/head";


const About = () => {
  return (
    <div>
      <Head>
        <title>Jordan Freelance</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/greyback.png" />
      </Head>
      <NavBar />
      <AboutHero />
      <LatestWork />
      <AboutMe />
      <HowICanHelp />
      <FoundersNote />


    </div>
  );
};

export default About;
