import Head from "next/head";
import CommunityHero from "../Components/CommunityHero/CommunityHero";


import NavBar from "../Components/NavBar/NavBar";


const Community = () => {
  return (
    <div>
      <Head>
        <title>Jordan Freelance</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/greyback.png" />
      </Head>
      <NavBar />
      <CommunityHero />


    </div>
  );
}

export default Community;