import Head from "next/head";
import Image from "next/image";
import HomeHero from "../Components/HomeHero/HomeHero";
import LogoList from "../Components/LogoList/LogoList";
import NavBar from "../Components/NavBar/NavBar";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Jordan Freelance</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/greyback.png" />
      </Head>
      <NavBar />
      <HomeHero />
      <LogoList />
    </div>
  );
}
