import Head from "next/head";
import BigSlateTitle from "../Components/BigSlateTitle/BigSlateTitle";
import Folders from "../Components/Folders/Folders";
import FoundersNote from "../Components/FoundersNote/FoundersNote";
import HomeHero from "../Components/HomeHero/HomeHero";
import HowICanHelp from "../Components/HowICanHelp/HowICanHelp";
import LatestWork from "../Components/LatestWork/LatestWork";
import LogoList from "../Components/LogoList/LogoList";
import MoreAboutMe from "../Components/MoreAboutMe/MoreAboutMe";
import NavBar from "../Components/NavBar/NavBar";
import styles from "../styles/Home.module.css";


import { createClient } from "contentful";

export async function getStaticProps() {
  const client = createClient({
    space: process.env.CONTENTFUL_SPACE_ID,
    accessToken: process.env.CONTENTFUL_ACCESS_KEY
  })

  const res = await client.getEntries({
    content_type: "latestWorkCarousel"
  })
  return {
    props: {
      latestWorkImg: res.items[0].fields.latestWorkCarousel.map((obj) => obj.fields.file)
    }
  }
}

export default function Home({ latestWorkImg }) {




export default function Home({ latestWorkUrls }) {

  return (
    <div className={styles.container}>
      <Head>
        <title>Jordan Freelance</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/greyback.png" />
      </Head>
      <NavBar />
      <HomeHero leftImg={"/images/leaves.png"} paragraph={`I’m a Front-end web developer who turned years of coding into a
            full-time career, and recently into my freelancing journey. I help
            teach hundreds of student how to find their own version of success
            through my articles, newsletter, products, and freelance community.`} />

      <LogoList />
      <Folders />

      <LatestWork latestWorkImg={latestWorkImg} />

      <HowICanHelp />
      <BigSlateTitle text={"More About Me"} />
      <MoreAboutMe />
      <FoundersNote />
    </div>
  );
}
