import Head from "next/head";
import BigSlateTitle from "../Components/BigSlateTitle/BigSlateTitle";
import Folders from "../Components/Folders/Folders";
import FoundersNote from "../Components/FoundersNote/FoundersNote";
import HomeHero from "../Components/HomeHero/HomeHero";
import HowICanHelp from "../Components/HowICanHelp/HowICanHelp";
import LatestWork from "../Components/LatestWork/LatestWork";
import LogoList from "../Components/LogoList/LogoList";
import MoreAboutMe from "../Components/MoreAboutMe/MoreAboutMe";
import NavBar from "../Components/NavBar/NavBar";
import styles from "../styles/Home.module.css";


import { createClient } from "contentful";
import { useEffect, useState } from "react";

export async function getStaticProps() {
  const client = createClient({
    space: process.env.CONTENTFUL_SPACE_ID,
    accessToken: process.env.CONTENTFUL_ACCESS_KEY
  })

  const res = await client.getEntries({
    content_type: "latestWorkCarousel"
  })
  return {
    props: {
      latestWorkImg: res.items[0].fields.latestWorkCarousel.map((obj) => obj.fields.file)
    }
  }
}


export default function Home({ latestWorkImg }) {




  const [scrollY, setScrollY] = useState(0);
  useEffect(() => {
    const handleScroll = () => {
      setScrollY(window.scrollY / 2);
    };

    // just trigger this so that the initial state 
    // is updated as soon as the component is mounted
    // related: https://stackoverflow.com/a/63408216
    handleScroll();

    window.addEventListener("scroll", handleScroll);
    return () => {
      window.removeEventListener("scroll", handleScroll);
    };

    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);




  return (
    <div className={styles.container}>
      <Head>
        <title>Home - Jordan Freelance</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/greyback.png" />
      </Head>
      <NavBar />
      <HomeHero scrollY={scrollY} leftImg={"/images/leaves.png"} paragraph={`
      I upgrade, fix and in all respects make your websites better.
      I make it my mission to be the most dependable & honest expertise developer you know
      `} />

      <LogoList />
      <Folders scrollY={scrollY} />

      <LatestWork latestWorkImg={latestWorkImg} />

      <HowICanHelp />
      <BigSlateTitle text={"More About Me"} />
      <MoreAboutMe />
      <FoundersNote />
    </div>
  );
}
