import Head from "next/head";
import NavBar from "../Components/NavBar/NavBar";
import HomeHero from "../Components/HomeHero/HomeHero"
import LogoList from "../Components/LogoList/LogoList";
import ProjectAndText from "../Components/ProjectAndText/ProjectAndText";
import SkillsAndProject from "../Components/SkillsAndProject/SkillsAndProject";
import LatestWork from "../Components/LatestWork/LatestWork"
import FoundersNote from "../Components/FoundersNote/FoundersNote"
import { createClient } from "contentful";
import { Project1, Project2 } from "../Components/02-Constants/ArticleDynamic";


export async function getStaticProps() {
  const client = createClient({
    space: process.env.CONTENTFUL_SPACE_ID,
    accessToken: process.env.CONTENTFUL_ACCESS_KEY
  })

  const res = await client.getEntries({
    content_type: "latestWorkCarousel"
  })
  return {
    props: {
      latestWorkImg: res.items[0].fields.latestWorkCarousel.map((obj) => obj.fields.file)
    }
  }
}


const Projects = ({ latestWorkImg }) => {
  return (
    <div>
      <Head>
        <title>Projects - Jordan Freelance</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/greyback.png" />
      </Head>
      <NavBar />
      <HomeHero
        LeftSectionIMG={'url("/images/whiteMarbleTexture.jpg")'}
        RightSectionIMG={'url("/images/whiteWavesTexture.jpg")'}
        heading={<h1 style={{ fontSize: "4rem", color: "#23C7A7", marginBottom: "40px" }}>My Projects</h1>}
        show3D={true}
        paragraph={`Check out my recent projects and learn how to create your own along the way with my free articles when you sign up, after years of experience designing and coding websites i show the best route to creating unique, user friendly and accessaible web application's `} />
      <LogoList />
      <ProjectAndText slateText={"Project 1"} img1="/images/phone1/bikeman1.png"
        projects={Project1}
        img2="/images/phone1/bikeman2.png"
        img3="/images/phone1/bikeman3.png"
        img4="/images/phone1/bikeman4.png"
        img5="/images/phone1/bikeman5.png" />

      <SkillsAndProject />

      <ProjectAndText slateText={"Project 2"}
        projects={Project2}
        direction={"row-reverse"} img1="/images/phone2/groPro1.png"
        img2="/images/phone2/groPro2.png"
        img3="/images/phone2/groPro3.png"
        img4="/images/phone2/groPro4.png"
        img5="/images/phone2/groPro5.png" />
      <LatestWork latestWorkImg={latestWorkImg} />
      <FoundersNote />


    </div>
  );
}

export default Projects;